---

### INSTRUCTIONS AND INFORMATION ###
#
# 1. Run the play with the command: 'ansible-playbook agent_newrelic/deploy_infra_agent.yml --extra-vars "env=<hostlist>"'
#
# Author: Scott Champine
# Objective: Deploy New Relic Infra Agent across all servers
# Date: 10/15/2019
# Revision: 10/17/2019 - To work with both RHEL6 and 7 servers.
#
###

- hosts: "{{ env }}"
  remote_user: root
  gather_facts: True
  vars:
    workdir: /usr/local/scripts/ansible/files/newrelic_files
  tasks:

  - name: Push over RHEL 7 file for newrelic-infra deploy
    copy:
      src: "{{workdir}}/RHEL7-newrelic-infra-1.5.51-1.x86_64.rpm"
      dest: /root/newrelic-infra-1.5.51-1.x86_64.rpm
    when: ansible_distribution_major_version == "7"

  - name: Push over RHEL 6 file for newrelic-infra deploy
    copy:
      src: "{{workdir}}/RHEL6-newrelic-infra-1.5.59-1.x86_64.rpm"
      dest: /root/newrelic-infra-1.5.59-1.x86_64.rpm
    when: ansible_distribution_major_version == "6"

  - name: Push over newrelic_files/newrelic directory to /opt/newrelic
    copy:
      src: "{{workdir}}/newrelic-infra.yml"
      dest: /etc/newrelic-infra.yml

  - name: Deploy the RHEL 7 RPM via RPM
    yum:
      name: /root/newrelic-infra-1.5.51-1.x86_64.rpm
      state: present
    when: ansible_distribution_major_version == "7"

  - name: Deploy the RHEL 6 RPM via RPM
    yum:
      name: /root/newrelic-infra-1.5.59-1.x86_64.rpm
      state: present
    when: ansible_distribution_major_version == "6"

  - name: Set the newrelic-infra service to on
    service:
      name: newrelic-infra
      state: started
      enabled: yes
